# -*- coding: utf-8 -*-
"""opencv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KSWnkof_a1CTtSE0BcJVFjrPY0YoN47
"""

!pip install streamlit
!pip install opencv-python-headless
!pip install pytesseract
import streamlit as st
import cv2
import numpy as np
from PIL import Image
import pytesseract


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="OpenCV Computer Vision Lab",
    page_icon="👁️",
    layout="wide"
)


# --------------------------------------------------
# Title
# --------------------------------------------------

st.title("👁️ OpenCV Computer Vision Lab")

st.write(
    "Upload an image and test different Computer Vision "
    "techniques using OpenCV."
)


# --------------------------------------------------
# Sidebar
# --------------------------------------------------

st.sidebar.header("Computer Vision Techniques")

technique = st.sidebar.selectbox(
    "Choose a technique:",
    [
        "Original Image",
        "Image Information",
        "Grayscale",
        "Resize",
        "Rotate",
        "Gaussian Blur",
        "Threshold",
        "Canny Edge Detection",
        "Contours",
        "Draw Rectangle",
        "Add Text",
        "OCR - Extract Text"
    ]
)


# --------------------------------------------------
# Upload Image
# --------------------------------------------------

uploaded_file = st.file_uploader(
    "Upload an image",
    type=["jpg", "jpeg", "png"]
)


# --------------------------------------------------
# Main Processing
# --------------------------------------------------

if uploaded_file is not None:

    # Read uploaded image
    image_pil = Image.open(uploaded_file).convert("RGB")

    # Convert PIL → NumPy
    image = np.array(image_pil)

    # Convert RGB → BGR for OpenCV
    image = cv2.cvtColor(
        image,
        cv2.COLOR_RGB2BGR
    )

    # --------------------------------------------------
    # Original Image
    # --------------------------------------------------

    if technique == "Original Image":

        output = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption="Original Image",
            use_container_width=True
        )


    # --------------------------------------------------
    # Image Information
    # --------------------------------------------------

    elif technique == "Image Information":

        height, width, channels = image.shape

        st.subheader("Image Information")

        col1, col2, col3 = st.columns(3)

        col1.metric("Width", width)
        col2.metric("Height", height)
        col3.metric("Channels", channels)

        st.write(
            f"Image shape: `{image.shape}`"
        )

        output = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption="Image",
            use_container_width=True
        )


    # --------------------------------------------------
    # Grayscale
    # --------------------------------------------------

    elif technique == "Grayscale":

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2GRAY
        )

        st.subheader("Grayscale Image")

        st.image(
            gray,
            caption="Grayscale",
            use_container_width=True,
            clamp=True
        )


    # --------------------------------------------------
    # Resize
    # --------------------------------------------------

    elif technique == "Resize":

        scale = st.slider(
            "Scale",
            min_value=0.1,
            max_value=2.0,
            value=0.5,
            step=0.1
        )

        height, width = image.shape[:2]

        new_width = int(width * scale)
        new_height = int(height * scale)

        resized = cv2.resize(
            image,
            (new_width, new_height)
        )

        output = cv2.cvtColor(
            resized,
            cv2.COLOR_BGR2RGB
        )

        st.write(
            f"New size: `{new_width} × {new_height}`"
        )

        st.image(
            output,
            caption="Resized Image",
            use_container_width=True
        )


    # --------------------------------------------------
    # Rotate
    # --------------------------------------------------

    elif technique == "Rotate":

        angle = st.slider(
            "Rotation Angle",
            -180,
            180,
            45
        )

        height, width = image.shape[:2]

        center = (
            width // 2,
            height // 2
        )

        matrix = cv2.getRotationMatrix2D(
            center,
            angle,
            1.0
        )

        rotated = cv2.warpAffine(
            image,
            matrix,
            (width, height)
        )

        output = cv2.cvtColor(
            rotated,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption=f"Rotated {angle}°",
            use_container_width=True
        )


    # --------------------------------------------------
    # Gaussian Blur
    # --------------------------------------------------

    elif technique == "Gaussian Blur":

        kernel_size = st.slider(
            "Kernel Size",
            3,
            15,
            5,
            step=2
        )

        blur = cv2.GaussianBlur(
            image,
            (kernel_size, kernel_size),
            0
        )

        output = cv2.cvtColor(
            blur,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption="Gaussian Blur",
            use_container_width=True
        )


    # --------------------------------------------------
    # Threshold
    # --------------------------------------------------

    elif technique == "Threshold":

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2GRAY
        )

        threshold_value = st.slider(
            "Threshold Value",
            0,
            255,
            127
        )

        _, threshold = cv2.threshold(
            gray,
            threshold_value,
            255,
            cv2.THRESH_BINARY
        )

        st.image(
            threshold,
            caption="Binary Threshold",
            use_container_width=True,
            clamp=True
        )


    # --------------------------------------------------
    # Canny Edge Detection
    # --------------------------------------------------

    elif technique == "Canny Edge Detection":

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2GRAY
        )

        blur = cv2.GaussianBlur(
            gray,
            (5, 5),
            0
        )

        lower = st.slider(
            "Lower Threshold",
            0,
            255,
            50
        )

        upper = st.slider(
            "Upper Threshold",
            0,
            255,
            150
        )

        edges = cv2.Canny(
            blur,
            lower,
            upper
        )

        st.image(
            edges,
            caption="Canny Edges",
            use_container_width=True,
            clamp=True
        )


    # --------------------------------------------------
    # Contours
    # --------------------------------------------------

    elif technique == "Contours":

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2GRAY
        )

        blur = cv2.GaussianBlur(
            gray,
            (5, 5),
            0
        )

        edges = cv2.Canny(
            blur,
            50,
            150
        )

        contours, hierarchy = cv2.findContours(
            edges,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )

        output = image.copy()

        cv2.drawContours(
            output,
            contours,
            -1,
            (0, 255, 0),
            2
        )

        output = cv2.cvtColor(
            output,
            cv2.COLOR_BGR2RGB
        )

        st.write(
            f"Number of contours detected: **{len(contours)}**"
        )

        st.image(
            output,
            caption="Detected Contours",
            use_container_width=True
        )


    # --------------------------------------------------
    # Draw Rectangle
    # --------------------------------------------------

    elif technique == "Draw Rectangle":

        output = image.copy()

        height, width = image.shape[:2]

        cv2.rectangle(
            output,
            (50, 50),
            (width - 50, height - 50),
            (0, 255, 0),
            3
        )

        output = cv2.cvtColor(
            output,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption="Rectangle",
            use_container_width=True
        )


    # --------------------------------------------------
    # Add Text
    # --------------------------------------------------

    elif technique == "Add Text":

        output = image.copy()

        cv2.putText(
            output,
            "OpenCV Computer Vision",
            (50, 100),
            cv2.FONT_HERSHEY_SIMPLEX,
            2,
            (255, 0, 0),
            4,
            cv2.LINE_AA
        )

        output = cv2.cvtColor(
            output,
            cv2.COLOR_BGR2RGB
        )

        st.image(
            output,
            caption="Text Added",
            use_container_width=True
        )


    # --------------------------------------------------
    # OCR
    # --------------------------------------------------

    elif technique == "OCR - Extract Text":

        st.subheader("🔍 OCR - Text Extraction")

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2GRAY
        )

        blur = cv2.GaussianBlur(
            gray,
            (3, 3),
            0
        )

        _, thresh = cv2.threshold(
            blur,
            200,
            255,
            cv2.THRESH_BINARY
        )

        col1, col2 = st.columns(2)

        with col1:

            st.write("### Original")

            original_rgb = cv2.cvtColor(
                image,
                cv2.COLOR_BGR2RGB
            )

            st.image(
                original_rgb,
                use_container_width=True
            )

        with col2:

            st.write("### Preprocessed")

            st.image(
                thresh,
                use_container_width=True,
                clamp=True
            )

        # OCR
        text = pytesseract.image_to_string(
            thresh,
            config="--psm 6"
        )

        st.write("### Extracted Text")

        st.text_area(
            "OCR Result",
            text,
            height=300
        )